package com.bookstore.entity;
// Generated Sep 1, 2019 11:43:21 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.*;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.Where;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "bookstoredb")
@SQLDelete(sql = "UPDATE category SET deleted = '1' WHERE category_id = ?")
//Filter added to retrieve only records that have not been soft deleted.
@Where(clause = "deleted <> '1'")
@NamedQueries({ @NamedQuery(name = "Category.findAll", query = "SELECT c FROM Category c ORDER BY c.name"),
		@NamedQuery(name = "Category.countAll", query = "SELECT COUNT(c.categoryId) FROM Category c"),
		@NamedQuery(name = "Category.findByName", query = "SELECT c FROM Category c WHERE c.name=:name") })
public class Category implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer categoryId;
	private String name;
	private Set<Book> books = new HashSet<Book>(0);
	private boolean deleted;

	public Category() {
	}

	public Category(String name) {
		//super();
		this.name = name;
	}
	public Category(String name, boolean deleted) {
		this.name = name;
		this.deleted = deleted;
	}

	public Category(String name, boolean deleted, Set<Book> books) {
		this.name = name;
		this.deleted = deleted;
		this.books = books;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}
