package com.bookstore.entity;
// Generated Sep 20, 2019 1:21:56 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "bookstoredb")
@NamedQueries({ @NamedQuery(name = "Employee.findAll", query = "SELECT e FROM Employee e ORDER BY e.fullName"),
		@NamedQuery(name = "Employee.findByEmail", query = "SELECT e FROM Employee e where e.email=:email"),
		@NamedQuery(name = "Employee.countAll", query = "SELECT Count(e.employeeId) FROM Employee e"),
		@NamedQuery(name = "Employee.checkLogin", query = "SELECT e FROM Employee e WHERE e.email=:email AND e.password=:password")

})
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer employeeId;
	private String fullName;
	private String email;
	private String password;
	private String confirmPassword;
	private String address;
	private String phoneNumber;
	private String city;

	public Employee() {
	}

	public Employee(String email, String password) {
		super();
		this.email = email;
		this.password = password;
	}

	public Employee(String fullName, String address, String phoneNumber, String email, String password,
			String confirmPassword, String city) {
		super();
		this.fullName = fullName;
		this.email = email;
		this.password = password;
		this.confirmPassword = confirmPassword;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.city = city;
	}

	public Employee(Integer employeeId, String fullName, String address, String phoneNumber, String email,
			String password, String confirmPassword, String city) {
		this(fullName, address, phoneNumber, email, password, confirmPassword, city);
		this.employeeId = employeeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "employee_Id", unique = true, nullable = false)
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "fullName", nullable = false, length = 45)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "confirmPassword", nullable = false, length = 45)
	public String getConfirmPassword() {
		return this.confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	@Column(name = "address", nullable = false, length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phoneNumber", nullable = false)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
