package com.bookstore.entity;
// Generated Oct 15, 2019 9:22:02 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "bookstoredb")
@NamedQueries({
	@NamedQuery(name = "Payment.findAll",query = "SELECT p FROM Payment p ORDER BY p.nameCard DESC"),
	@NamedQuery(name = "Payment.countAll",query = "SELECT COUNT(p.expiratinDate) FROM Payment p")
})
public class Payment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer paymentId;
	private String nameCard;
	private String cardNumber;
	private String expiratinDate;
	private int cvc;

	public Payment() {
	}

	public Payment(String nameCard, String cardNumber, String expiratinDate, int cvc) {
		this.nameCard = nameCard;
		this.cardNumber = cardNumber;
		this.expiratinDate = expiratinDate;
		this.cvc = cvc;
	}
	
	public Payment( Integer paymentId,String nameCard, String cardNumber, String expiratinDate, int cvc) {
		this.paymentId=paymentId;
		this.nameCard = nameCard;
		this.cardNumber = cardNumber;
		this.expiratinDate = expiratinDate;
		this.cvc = cvc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_id", unique = true, nullable = false)
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "nameCard", nullable = false, length = 45)
	public String getNameCard() {
		return this.nameCard;
	}

	public void setNameCard(String nameCard) {
		this.nameCard = nameCard;
	}

	@Column(name = "cardNumber", nullable = false)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "expiratinDate", nullable = false, length = 16)
	public String getExpiratinDate() {
		return this.expiratinDate;
	}

	public void setExpiratinDate(String expiratinDate) {
		this.expiratinDate = expiratinDate;
	}

	@Column(name = "cvc", nullable = false)
	public int getCvc() {
		return this.cvc;
	}

	public void setCvc(int cvc) {
		this.cvc = cvc;
	}

}
